from collections import namedtuple

from saveregions import GADM

# Define a namedtuple for easier access to country codes and their GADM objects
Country = namedtuple("Country", ["code", "gadm"])

# Define the list of African countries with their codes and GADM objects
africa = [
    Country("AO", GADM([], "Angola")),
    Country("BF", GADM([], "Burkina Faso")),
    Country("BI", GADM([], "Burundi")),
    Country("BJ", GADM([], "Benin")),
    Country("BW", GADM([], "Botswana")),
    Country("CD", GADM([], "Democratic Republic of the Congo")),
    Country("CF", GADM([], "Central African Republic")),
    Country("CG", GADM([], "Republic of Congo")),
    Country("CI", GADM([], "Côte d'Ivoire")),
    Country("CM", GADM([], "Cameroon")),
    Country("CV", GADM([], "Cape Verde")),
    Country("DJ", GADM([], "Djibouti")),
    Country("DZ", GADM([], "Algeria")),
    Country("EG", GADM([], "Egypt")),
    Country("EH", GADM([], "Western Sahara")),
    Country("ER", GADM([], "Eritrea")),
    Country("ET", GADM([], "Ethiopia")),
    Country("GA", GADM([], "Gabon")),
    Country("GH", GADM([], "Ghana")),
    Country("GM", GADM([], "Gambia")),
    Country("GN", GADM([], "Guinea")),
    Country("GQ", GADM([], "Equatorial Guinea")),
    Country("GW", GADM([], "Guinea-Bissau")),
    Country("KE", GADM([], "Kenya")),
    Country("KM", GADM([], "Comoros")),
    Country("LR", GADM([], "Liberia")),
    Country("LS", GADM([], "Lesotho")),
    Country("LY", GADM([], "Libya")),
    Country("MA", GADM([], "Morocco")),
    Country("MG", GADM([], "Madagascar")),
    Country("ML", GADM([], "Mali")),
    Country("MR", GADM([], "Mauritania")),
    Country("MU", GADM([], "Mauritius")),
    Country("MW", GADM([], "Malawi")),
    Country("MZ", GADM([], "Mozambique")),
    Country("NA", GADM([], "Namibia")),
    Country("NE", GADM([], "Niger")),
    Country("NG", GADM([], "Nigeria")),
    Country("RE", GADM([], "Reunion")),
    Country("RW", GADM([], "Rwanda")),
    Country("SC", GADM([], "Seychelles")),
    Country("SD", GADM([], "Sudan")),
    Country("SL", GADM([], "Sierra Leone")),
    Country("SN", GADM([], "Senegal")),
    Country("SO", GADM([], "Somalia")),
    Country("SS", GADM([], "South Sudan")),
    Country("ST", GADM([], "São Tomé and Príncipe")),
    Country("SZ", GADM([], "Swaziland")),
    Country("TD", GADM([], "Chad")),
    Country("TG", GADM([], "Togo")),
    Country("TN", GADM([], "Tunisia")),
    Country("TZ", GADM([], "Tanzania")),
    Country("UG", GADM([], "Uganda")),
    Country("YT", GADM([], "Mayotte")),
    Country("ZA", GADM([], "South Africa")),
    Country("ZM", GADM([], "Zambia")),
    Country("ZW", GADM([], "Zimbabwe")),
]
